### ISSUE TITLE
Why Force use Application as context ?

### ISSUE THREAD

**Issue by zackdu35** [vanniktech/RxPermission#47]
I'm using your library in our project (which is an android library project) and i noticed that I can't instanciate the RealRxPermission because I have no Application Object.

It would be suitable to use the Context object rather than Application.

```
static RxRealPermissionExtended instance;

    public static RxRealPermissionExtended getInstance(final Context context) {
        synchronized (RealRxPermission.class) {
            if (instance == null) {
                instance = new RxRealPermissionExtended(context);
            }
        }

        return instance;
    }
```

**Comment by vanniktech** [comment]
Like to be explicit when passing in. What would you like to use instead?

**Comment by zackdu35** [comment]
I have updated my first post.

**Comment by vanniktech** [comment]
If you have a Context you can use getApplicationContext.

**Comment by zackdu35** [comment]
Thank you !

**Comment by vanniktech** [comment]
I might change the signature and do it internally. For now I'll close this issue though.
