### ISSUE TITLE
Choice for answer subscribe

### ISSUE THREAD

**Issue by tonywis** [vanniktech/RxPermission#50]
Hi,

We use your library for use with  contexts in parameter and the ability to process the responses for each permission request.

But sometime, we want request many permission but we want to know if ALL permissions are granted, a litle like the tbruyelle lib in once time callback. So can you thinks if it's possible to have that ? To have more choice for the using of library.

Tony

**Comment by vanniktech** [comment]
You can use `Observable<Permission> requestEach(String... permissions);`. If the permission is granted (it checks that) it just emits multiple Permission instances which are all granted.

https://github.com/vanniktech/RxPermission/blob/dbc32db35face5792f2bc205034fa786d30d8d59/library/src/main/java/com/vanniktech/rxpermission/RealRxPermission.java#L115

**Comment by vanniktech** [comment]
The above thing should handle your feature request. In case it does not reply or create a new issue please.

**Comment by tonywis** [comment]
Hi, sorry, I know you want me to create a new number but it's in continuity, beacause, the subscribe on requestEach() (for example 3 permissions) called 3 times, beacause each permission emit result. But it possible to have an only one emit with boolean param granted or not granted for all parameters ?

**Comment by vanniktech** [comment]
Use `Observable#toList()`
