### ISSUE TITLE
minSDK 15 ?

### ISSUE THREAD

**Issue by tonywis** [vanniktech/RxPermission#53]
Hi,

I would like to know why rxPermission is minSDK 15 and not 14?

Is it possible to put it minSDK 14 ?

Because we use it in projects cordova 6 and for technical reasons we have not yet mounted in minSDK greater than 14.

**Comment by vanniktech** [comment]
Support libraries are nowadays also at 15. I'm just leaning on that one, to be honest. I'm surprised anyone is using 14.

**Comment by tonywis** [comment]
Cordova use default minSDK 14 and in our mobile park there are still some mobile API 14.

But if it's impossible to downgrade minSDK to 14 for rxPermission, it's not a problem but that would arrange us.

**Comment by vanniktech** [comment]
I think it should be just fine. Happy to take a PR that lowers it if you verify that it works on your side.

**Comment by tonywis** [comment]
It's ok. :)

**Comment by vanniktech** [comment]
It's ok to?

**Comment by tonywis** [comment]
I have tested rxPermission with minSDK 14 and build this in android with API 14 and it works.

**Comment by tonywis** [comment]
Hi,
so what do you think about that ? Some of our developments are waiting for the answer you will give about that. =)

**Comment by tonywis** [comment]
Oh sorry, I had misunderstood 'PR' x)
I'm doing test and I will do a PR.

**Comment by vanniktech** [comment]
Fixed by #54

Thank you!
