### ISSUE TITLE
No response after sending singleTask Activity to the background

### ISSUE THREAD

**Issue by miguelvillasenor** [vanniktech/RxPermission#66]
The library doesn't show the permissions activity again if a single task activity is sent to the background while showing the permissions dialog and then is reopened from the application icon.

**Prerequisites:**

Require the permissions from an activity with launchMode = singleTask

**The steps to reproduce are:**

1. Trigger the permission request.
2. See the permission dialog on the screen.
3. Without approving or denying the permission send the app to the background.
4. Reopen the app from the application Icon, reopening it from the task manager won't trigger the issue.

**Result**:

The permission dialog won't be displayed to the user.

**Example:**

`AndroidManifest.xml`
```
 ...
   <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity android:name=".MainActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
   ...
```

`MainActivity.kt`

```
   private val disposables = CompositeDisposable()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        requestPermission.setOnClickListener {
            val disposable = RealRxPermission.getInstance(this)
                .requestEach(Manifest.permission.CAMERA)
                .subscribe()
            disposables.add(disposable)
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        disposables.clear()
    }
```

I was able to track the issue, until the point of identifying that `RealRxPermission.currentPermissionRequests` permission requests are never cleared in this specific case as the`onRequestPermissionsResult` method is never called even when the ShadowActivity is dismissed

**Comment by vanniktech** [comment]
This is, if I understand your issue correctly, working as intended. There's more information in #51
