### ISSUE TITLE
When one of requestEach is denied, callback is not fired

### ISSUE THREAD

**Issue by zhombie** [vanniktech/RxPermission#69]
Maybe it will be useful to return something if one of requested permissions is denied

**Comment by vanniktech** [comment]
If you request A & B permissions and A is accepted and B isn't, it should give you two results back. Are you saying this is not the case?

**Comment by zhombie** [comment]
I subscribed to bundle of permissions, let's say **CAMERA** & **WRITE_EXTERNAL_STORAGE**,
then firstly, if I accept Camera at first, secondly decline Write External Storage, so there is no any response. My realization at bottom:

```
permissions.subscribe { permission ->
   when (permission.state()) {
      Permission.State.GRANTED -> {}
      Permission.State.DENIED -> {}
      ...
   }
}
```
Am i doing anything wrong?

**Comment by zhombie** [comment]
> I subscribed to bundle of permissions, let's say **CAMERA** & **WRITE_EXTERNAL_STORAGE**,
> then firstly, if I accept Camera at first, secondly decline Write External Storage, so there is no any response. My realization at bottom:
> 
> ```
> permissions.subscribe { permission ->
>    when (permission.state()) {
>       Permission.State.GRANTED -> {}
>       Permission.State.DENIED -> {}
>       ...
>    }
> }
> ```
> 
> Am i doing anything wrong?

It means

**Comment by vanniktech** [comment]
Can you try to reproduce this in the sample app?

**Comment by zhombie** [comment]
I have already reproduced, that's why I'm writing to you :D

**Comment by vanniktech** [comment]
Well. In your project which I have no access too. Reproduce it in the sample app, come up with a PR or something that is easy to checkout and I might find the time to have a look at your issue. This is open source after all ;)

**Comment by zhombie** [comment]
Actually, I have already wrote it down on top. There is no any difficult stuffs, I just want to handle each permission.
