### ISSUE TITLE
Android Q Location Permission Request

### ISSUE THREAD

**Issue by PRobi23** [vanniktech/RxPermission#72]
Hello,

In android q there is a new permission: ACCESS_BACKGROUND_LOCATION.

If you access this permission than the user can choose from three options:
Allow all the time
Allow only while using app
Deny

I would like to have answer granted in the first two case, can you make your library work like it? Actually i receive a denied which is not true. Maybe a new value can be added to the state enum (PERMANENTLY_GRANTED) or something similar, and the user can decide what should do with it.

Thanks

**Comment by vanniktech** [comment]
Yeah still need to adjust my apps with this new permission request

**Comment by PRobi23** [comment]
What do you think, when this change can be ready? I would need to use it in my application (this is an existing bug from the client).

**Comment by vanniktech** [comment]
Hard to say. It's a matter of weeks though

**Comment by PRobi23** [comment]
Thanks, please let me know, if you finished it.

**Comment by vanniktech** [comment]
From my opinion there's nothing this library needs to do different. Have a look at https://github.com/vanniktech/RxPermission/pull/73

Therefore I'm closing, but please if you feel otherwise convince me.
