### ISSUE TITLE
Feature request - RequestEach combined like tbruyelle / RxPermissions

### ISSUE THREAD

**Issue by merlinJeyakumar** [vanniktech/RxPermission#74]
when i try to combine multiple permission callback as single,
Now I am writing :
RealRxPermission.getInstance(application)
                .requestEach(
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_COARSE_LOCATION
                ).subscribe({
                                  if (it.name() == Manifest.permission.ACCESS_COARSE_LOCATION) {
                                 // if granted or denied
                                 }
})

same way tbruyelle RxPermissions having this feature but havin an issue while using it 
rxPermissions
    .requestEachCombined(Manifest.permission.CAMERA,
             Manifest.permission.READ_PHONE_STATE)

**Comment by vanniktech** [comment]
`.all(permission -> permission.state() == GRANTED)` if you want a `Single<Boolean>` otherwise use `Single#toList()`

**Comment by vanniktech** [comment]
There's more history here: https://github.com/vanniktech/RxPermission/pull/52
