### ISSUE TITLE
Upgrade to rxjava 3

### ISSUE THREAD

**Issue by olsisaqe** [vanniktech/RxPermission#75]
As the rxjava 3 is gaining popularity and is mostly backward compatible, would be beneficial to upgrade this library to use rxjava 3.  Like this there wouldn't be any need to use the rxjava2 to rxjava3 [bridge](https://github.com/akarnokd/RxJavaBridge) library.

**Comment by vanniktech** [comment]
Good hearing from you. Want to create a PR? I've not migrated to RxJava 3 in any project.

**Comment by vanniktech** [comment]
And I don't plan to in the near future.

**Comment by olsisaqe** [comment]
Hey, good to hear from you as well. Would  be nice to catch up at some point in the future. 
Any specific reason why you didn't upgrade yet to RxJava3 (beside time)? Api is almost totally compatible.

**Comment by vanniktech** [comment]
Not worth the effort. RxJava 3 is just rxjava 2 with a different package and 5% nicer APIs. At some point, I'll probably need to since RxJava 2 won't be supported forever.

**Comment by vanniktech** [comment]
Not planning to do any time in the near future.
